/**
 * 20th Congress — Senate of the Philippines (24 members).
 * Cohort + party from Wikipedia election lists (accessed 2026).
 * Portraits: Wikimedia Commons — CC BY-SA / public domain per file page.
 */
const BAYAN_SENATE_ROSTER = [
  // —— Elected 2025 (term June 30, 2025 – June 30, 2031) ——
  {
    fullName: "Christopher Lawrence \"Bong\" Go",
    displayName: "Bong Go",
    slug: "bong-go",
    party: "Partido Demokratiko Pilipino",
    cohort: 2025,
    term: "2025–2031",
    wiki: "Bong_Go",
    photoFile: "Christopher Lawrence T. Go, Senate portrait 2025.png",
  },
  {
    fullName: "Paolo Benigno \"Bam\" Aquino IV",
    displayName: "Bam Aquino",
    slug: "bam-aquino",
    party: "Katipunan ng Nagkakaisang Pilipino",
    cohort: 2025,
    term: "2025–2031",
    wiki: "Bam_Aquino",
    photoFile: "Paolo Benigno \"Bam\" Aquino IV, Senate portrait 2025.png",
  },
  {
    fullName: "Ronald \"Bato\" dela Rosa",
    displayName: "Ronald dela Rosa",
    slug: "bato-delarosa",
    party: "Partido Demokratiko Pilipino",
    cohort: 2025,
    term: "2025–2031",
    wiki: "Ronald_dela_Rosa",
    photoFile: "Ronald \"Bato\" M. dela Rosa, Senate portrait 2025.png",
  },
  {
    fullName: "Erwin Tulfo",
    displayName: "Erwin Tulfo",
    slug: "erwin-tulfo",
    party: "Lakas–CMD",
    cohort: 2025,
    term: "2025–2031",
    wiki: "Erwin_Tulfo",
    photoFile: "Erwin T. Tulfo, Senate portrait 2025.png",
  },
  {
    fullName: "Francis \"Kiko\" Pangilinan",
    displayName: "Kiko Pangilinan",
    slug: "kiko-pangilinan",
    party: "Liberal Party",
    cohort: 2025,
    term: "2025–2031",
    wiki: "Kiko_Pangilinan",
    photoFile: "Francis \"Kiko\" Pangilinan, Senate portrait 2025.png",
  },
  {
    fullName: "Rodante Marcoleta",
    displayName: "Rodante Marcoleta",
    slug: "rodante-marcoleta",
    party: "Independent",
    cohort: 2025,
    term: "2025–2031",
    wiki: "Rodante_Marcoleta",
    photoFile: "Rodante D. Marcoleta, Senate portrait 2025.png",
  },
  {
    fullName: "Panfilo \"Ping\" Lacson",
    displayName: "Panfilo Lacson",
    slug: "ping-lacson",
    party: "Independent",
    cohort: 2025,
    term: "2025–2031",
    wiki: "Panfilo_Lacson",
    photoFile: "Panfilo \"Ping\" M. Lacson, Senate portrait 2025.png",
  },
  {
    fullName: "Vicente \"Tito\" Sotto III",
    displayName: "Tito Sotto",
    slug: "tito-sotto",
    party: "Nationalist People's Coalition",
    cohort: 2025,
    term: "2025–2031",
    wiki: "Tito_Sotto",
    photoFile: "Vicente C. Sotto III, Senate portrait 2025.png",
  },
  {
    fullName: "Pia Cayetano",
    displayName: "Pia Cayetano",
    slug: "pia-cayetano",
    party: "Nacionalista Party",
    cohort: 2025,
    term: "2025–2031",
    wiki: "Pia_Cayetano",
    photoFile: "Pia S. Cayetano, Senate portrait 2025.png",
  },
  {
    fullName: "Camille Villar",
    displayName: "Camille Villar",
    slug: "camille-villar",
    party: "Nacionalista Party",
    cohort: 2025,
    term: "2025–2031",
    wiki: "Camille_Villar",
    photoFile: "Camille A. Villar, Senate portrait 2025.png",
  },
  {
    fullName: "Manuel \"Lito\" Lapid",
    displayName: "Lito Lapid",
    slug: "lito-lapid",
    party: "Nationalist People's Coalition",
    cohort: 2025,
    term: "2025–2031",
    wiki: "Lito_Lapid",
    photoFile: "Manuel \"Lito\" M. Lapid, Senate portrait 2025.png",
  },
  {
    fullName: "Imee Marcos",
    displayName: "Imee Marcos",
    slug: "imee-marcos",
    party: "Nacionalista Party",
    cohort: 2025,
    term: "2025–2031",
    wiki: "Imee_Marcos",
    photoFile: "Imee R. Marcos, Senate portrait 2025.png",
  },
  // —— Elected 2022 (term June 30, 2022 – June 30, 2028) ——
  {
    fullName: "Robin Padilla",
    displayName: "Robin Padilla",
    slug: "robin-padilla",
    party: "PDP–Laban",
    cohort: 2022,
    term: "2022–2028",
    wiki: "Robin_Padilla",
    photoFile: "Robinhood C. Padilla, Senate portrait 2025.png",
    photoFileAlt: ["Robin Padilla.jpg"],
  },
  {
    fullName: "Loren Legarda",
    displayName: "Loren Legarda",
    slug: "loren-legarda",
    party: "Nationalist People's Coalition",
    cohort: 2022,
    term: "2022–2028",
    wiki: "Loren_Legarda",
    photoFile: "Senator Loren Legarda (Comission on Appointments portrait).png",
  },
  {
    fullName: "Raffy Tulfo",
    displayName: "Raffy Tulfo",
    slug: "raffy-tulfo",
    party: "Independent",
    cohort: 2022,
    term: "2022–2028",
    wiki: "Raffy_Tulfo",
    photoFile: "Senator Raffy Tulfo (Comission on Appointments portrait).png",
  },
  {
    fullName: "Sherwin Gatchalian",
    displayName: "Win Gatchalian",
    slug: "win-gatchalian",
    party: "Nationalist People's Coalition",
    cohort: 2022,
    term: "2022–2028",
    wiki: "Win_Gatchalian",
    photoFile: "Senator Sherwin \u201cWin\u201d Gatchalian, 2025 portrait (cropped).jpg",
  },
  {
    fullName: "Francis Escudero",
    displayName: "Chiz Escudero",
    slug: "chiz-escudero",
    party: "Nationalist People's Coalition",
    cohort: 2022,
    term: "2022–2028",
    wiki: "Francis_Escudero",
    photoFile: "Senate President Francis Escudero (cropped).jpg",
  },
  {
    fullName: "Mark Villar",
    displayName: "Mark Villar",
    slug: "mark-villar",
    party: "Nacionalista Party",
    cohort: 2022,
    term: "2022–2028",
    wiki: "Mark_Villar",
    photoFile: "Senator Mark Villar (Comission on Appointments portrait).png",
  },
  {
    fullName: "Alan Peter Cayetano",
    displayName: "Alan Peter Cayetano",
    slug: "alan-peter-cayetano",
    party: "Independent",
    cohort: 2022,
    term: "2022–2028",
    wiki: "Alan_Peter_Cayetano",
    photoFile: "Senator Alan Peter Cayetano (2022) (cropped).jpg",
  },
  {
    fullName: "Juan Miguel Zubiri",
    displayName: "Migz Zubiri",
    slug: "migz-zubiri",
    party: "Independent",
    cohort: 2022,
    term: "2022–2028",
    wiki: "Juan_Miguel_Zubiri",
    photoFile: "Senator Juan Miguel Zubiri (2022) (cropped).jpg",
  },
  {
    fullName: "Joel Villanueva",
    displayName: "Joel Villanueva",
    slug: "joel-villanueva",
    party: "Independent",
    cohort: 2022,
    term: "2022–2028",
    wiki: "Joel_Villanueva",
    photoFile: "Senator Joel Villanueva (Comission on Appointments portrait).png",
  },
  {
    fullName: "Joseph Victor Ejercito",
    displayName: "JV Ejercito",
    slug: "jv-ejercito",
    party: "Nationalist People's Coalition",
    cohort: 2022,
    term: "2022–2028",
    wiki: "JV_Ejercito",
    photoFile: "JV Ejercito 2025 (cropped).jpg",
  },
  {
    fullName: "Risa Hontiveros",
    displayName: "Risa Hontiveros",
    slug: "risa-hontiveros",
    party: "Akbayan",
    cohort: 2022,
    term: "2022–2028",
    wiki: "Risa_Hontiveros",
    photoFile: "Risa Hontiveros 2025 (Cropped).png",
  },
  {
    fullName: "Jinggoy Estrada",
    displayName: "Jinggoy Estrada",
    slug: "jinggoy-estrada",
    party: "Pwersa ng Masang Pilipino",
    cohort: 2022,
    term: "2022–2028",
    wiki: "Jinggoy_Estrada",
    photoFile: "Senator Jinggoy Estrada (Comission on Appointments portrait).png",
  },
];
window.BAYAN_SENATE_ROSTER = BAYAN_SENATE_ROSTER;
